# Site settings
baseurl = "http://kotazi.github.io/blog/"
languageCode = "en-us"
title = "kotazi.com"
theme = "kotazi.com"
canonifyurls = true

[params]
  name = "kotazi"
  description = "Hi, I'm web engineer"
  bio = ""
  # Enter optionally your twitter account
  twitter = "kotazi"
  # Disable comments by leaving disqusShortname empty
  disqusShortname = "spf13"
  # Enter your tracking code to enable Google Analytics
  googleAnalytics = "UA-70004407-1"
  enableRSS = true

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = ""
  subscribe = ""
  # Pagination links
  paginatePath = ""
  olderPosts = "次へ"
  newerPosts = "前へ"
  readMore = ""
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "Imagination and Realization"
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""